//! The host table: one row per coding assistant Estelle installs into.
//!
//! Kept apart from [`crate::host_install`]'s verbs because this file is DATA and that one is
//! behaviour, and because every row here is a claim that a customer's editor reads that exact
//! path. A row is added only with a citation to that host's own documentation — never to another
//! vendor's README describing it, and never to a guess. A host whose path could not be
//! established is deliberately ABSENT and named in the release notes: a wrong path writes into
//! somebody's editor configuration, which is strictly worse than a feature that is not there.
//!
//! ## Established from primary sources, 2026-09-19, and deliberately NOT added
//!
//! - **CodeBuddy (Tencent)** — its documentation site renders client-side, so no page could be
//!   read. Instruction path, AGENTS.md support, hooks and MCP are all unknown. Nothing is
//!   written for it.
//! - **OpenClaw** — documents `openclaw.json` and an `openclaw hooks` verb but never states the
//!   file's default location, so there is no path to write to.
//! - **Trae, user scope** — the project path `.trae/rules/` is confirmed; the global path is
//!   `~/.trae-cn/user_rules` on the CN build only and the international equivalent could not be
//!   read. The project row ships; the user column stays `None`.
//! - **Kilo Code, user scope** — global *instructions* live inside `~/.config/kilo/kilo.jsonc`
//!   as a JSON array, not as a rules file. Editing a customer's JSON config is a different and
//!   riskier mechanism than appending a delimited Markdown block, so it is not done here.
//! - **`~/.agents/skills/`** — real, and documented by Goose, which is why the Goose row uses it.
//!   It is NOT a standard: the SKILL.md format is standardised (agentskills.io) and says nothing
//!   about an install directory, and Claude Code reads `~/.claude/skills/` instead. Each row
//!   names its own path rather than assuming one convention covers the field.

use super::CURSOR_MDC_FRONTMATTER;
use super::DEVIN_RULE_FRONTMATTER;
use super::Host;
use super::KIRO_STEERING_FRONTMATTER;
use super::Shape;

/// Every host Estelle can install into, in descending order of likely customer count.
///
/// ⚠️ Adding a row is a claim that a customer's editor reads that exact path. Cite the host's own
/// documentation in the commit that adds it, never another vendor's README describing it.
pub(crate) const HOSTS: &[Host] = &[
    Host {
        name: "claude",
        label: "Claude Code",
        shapes: &[Shape::Instructions, Shape::Hook, Shape::Skill],
        project: Some("CLAUDE.md"),
        user: Some(".claude/CLAUDE.md"),
        legacy: &[],
        detect: Some(".claude"),
        skill: Some(".claude/skills/estelle/SKILL.md"),
        preamble: None,
        note: "The user-scope skill is the one that makes Estelle present before a repo is opened.",
    },
    Host {
        name: "codex",
        label: "Codex",
        shapes: &[Shape::Instructions, Shape::Hook],
        project: Some("AGENTS.md"),
        user: Some(".codex/AGENTS.md"),
        legacy: &["AGENT.md"],
        detect: Some(".codex"),
        skill: None,
        preamble: None,
        note: "Also a hook platform — `estelle install-hooks` writes ~/.codex/hooks.json.",
    },
    Host {
        name: "cursor",
        label: "Cursor",
        shapes: &[Shape::Instructions],
        project: Some(".cursor/rules/estelle.mdc"),
        user: None,
        legacy: &[".cursorrules"],
        detect: Some(".cursor"),
        skill: None,
        preamble: Some(CURSOR_MDC_FRONTMATTER),
        note: "A .mdc rule needs alwaysApply frontmatter; without it the rule is not always on.",
    },
    Host {
        name: "copilot",
        label: "GitHub Copilot",
        shapes: &[Shape::Instructions],
        project: Some(".github/copilot-instructions.md"),
        user: None,
        legacy: &[],
        detect: None,
        skill: None,
        preamble: None,
        note: "Repository-scoped only: Copilot reads the file out of the repo, not the home dir.",
    },
    Host {
        name: "windsurf",
        label: "Windsurf",
        shapes: &[Shape::Instructions],
        project: Some(".windsurf/rules/estelle.md"),
        user: None,
        legacy: &[".windsurfrules"],
        detect: Some(".codeium/windsurf"),
        skill: None,
        preamble: None,
        note: "Also an MCP client — `estelle init --client windsurf` writes the server entry.",
    },
    Host {
        name: "gemini",
        label: "Gemini CLI",
        shapes: &[Shape::Instructions],
        project: Some("GEMINI.md"),
        user: Some(".gemini/GEMINI.md"),
        legacy: &[],
        detect: Some(".gemini"),
        skill: None,
        preamble: None,
        note: "Instruction file only in this table; see the release notes on its hook surface.",
    },
    Host {
        name: "cline",
        label: "Cline",
        shapes: &[Shape::Instructions],
        project: Some(".clinerules"),
        user: None,
        legacy: &[],
        detect: None,
        skill: None,
        preamble: None,
        note: "Also an MCP client; its docs name AGENTS.md and ~/.agents/AGENTS.md as cross-tool formats.",
    },
    Host {
        name: "roo",
        label: "Roo Code",
        shapes: &[Shape::Instructions],
        project: Some(".roorules"),
        user: None,
        legacy: &[],
        detect: None,
        skill: None,
        preamble: None,
        note: "Roo Code shut down 2026-05-15; this row exists to refresh and REMOVE, not to reach it.",
    },
    Host {
        name: "junie",
        label: "JetBrains Junie",
        shapes: &[Shape::Instructions],
        project: Some(".junie/guidelines.md"),
        user: None,
        legacy: &[],
        detect: Some(".junie"),
        skill: None,
        preamble: None,
        note: "Also an MCP client — `estelle init --client jetbrains` writes the server entry.",
    },
    Host {
        name: "goose",
        label: "Goose",
        shapes: &[Shape::Instructions, Shape::Skill],
        project: Some(".goosehints"),
        user: Some(".config/goose/.goosehints"),
        legacy: &[],
        detect: Some(".config/goose"),
        skill: Some(".agents/skills/estelle/SKILL.md"),
        preamble: None,
        note: "Reads AGENTS.md then .goosehints; ~/.agents/skills is its documented skill root.",
    },
    Host {
        name: "qwen",
        label: "Qwen Code",
        shapes: &[Shape::Instructions],
        project: Some("QWEN.md"),
        user: None,
        legacy: &[],
        detect: Some(".qwen"),
        skill: None,
        preamble: None,
        note: "Gemini CLI fork with its own context filename.",
    },
    Host {
        name: "agents",
        label: "AGENTS.md (cross-vendor)",
        shapes: &[Shape::Instructions],
        project: Some("AGENTS.md"),
        user: None,
        legacy: &[".rules"],
        detect: None,
        skill: None,
        preamble: None,
        note: "The shared standard. One file reaches every host that honours it, Codex included.",
    },
    Host {
        name: "kiro",
        label: "Kiro",
        shapes: &[Shape::Instructions],
        project: Some(".kiro/steering/estelle.md"),
        user: Some(".kiro/steering/estelle.md"),
        legacy: &[],
        detect: Some(".kiro"),
        skill: None,
        preamble: Some(KIRO_STEERING_FRONTMATTER),
        note: "A steering file; inclusion: always is written out rather than assumed.",
    },
    Host {
        name: "droid",
        label: "Factory Droid",
        shapes: &[Shape::Instructions],
        project: Some("AGENTS.md"),
        user: Some(".factory/AGENTS.md"),
        legacy: &[],
        detect: Some(".factory"),
        skill: None,
        preamble: None,
        note: "Reads AGENTS.md from the repo and ~/.factory; its own docs warn against file sprawl.",
    },
    Host {
        name: "devin",
        label: "Devin CLI",
        shapes: &[Shape::Instructions],
        project: Some(".devin/rules/estelle.md"),
        user: Some(".config/devin/AGENTS.md"),
        legacy: &[],
        detect: Some(".config/devin"),
        skill: None,
        preamble: Some(DEVIN_RULE_FRONTMATTER),
        note: "The user path is XDG-shaped on macOS and Linux; Windows uses %APPDATA%, untested.",
    },
    Host {
        name: "antigravity",
        label: "Google Antigravity",
        shapes: &[Shape::Instructions],
        project: Some(".agents/rules/estelle.md"),
        user: None,
        legacy: &[],
        detect: None,
        skill: None,
        preamble: None,
        note: "Its global rules file IS ~/.gemini/GEMINI.md — reach that with `--host gemini`.",
    },
    Host {
        name: "pi",
        label: "Pi (Earendil)",
        shapes: &[Shape::Instructions],
        project: Some("AGENTS.md"),
        user: Some(".pi/agent/AGENTS.md"),
        legacy: &[],
        detect: Some(".pi"),
        skill: None,
        preamble: None,
        note: "Reads AGENTS.md or CLAUDE.md walking up from the cwd, plus the global file.",
    },
    Host {
        name: "amp",
        label: "Amp (Sourcegraph)",
        shapes: &[Shape::Instructions],
        project: Some("AGENTS.md"),
        user: Some(".config/amp/AGENTS.md"),
        legacy: &[],
        detect: Some(".config/amp"),
        skill: None,
        preamble: None,
        note: "Reads AGENTS.md natively, falling back to AGENT.md then CLAUDE.md when it is absent.",
    },
    Host {
        name: "opencode",
        label: "opencode",
        shapes: &[Shape::Instructions],
        project: Some("AGENTS.md"),
        user: Some(".config/opencode/AGENTS.md"),
        legacy: &[],
        detect: Some(".config/opencode"),
        skill: None,
        preamble: None,
        note: "AGENTS.md is opencode's own rules format, not an add-on; CLAUDE.md is its legacy fallback.",
    },
    Host {
        name: "kimi",
        label: "Kimi Code",
        shapes: &[Shape::Instructions],
        project: Some("AGENTS.md"),
        user: Some(".kimi-code/AGENTS.md"),
        legacy: &[],
        detect: Some(".kimi-code"),
        skill: None,
        preamble: None,
        note: "Its docs also point at ~/.agents/AGENTS.md for cross-tool instructions.",
    },
    Host {
        name: "hermes",
        label: "Hermes",
        shapes: &[Shape::Instructions],
        project: Some("AGENTS.md"),
        user: None,
        legacy: &[],
        detect: Some(".hermes"),
        skill: None,
        preamble: None,
        note: "AGENTS.md sits in its documented priority chain; ~/.hermes/SOUL.md is a persona file, not ours.",
    },
    Host {
        name: "kilo",
        label: "Kilo Code",
        shapes: &[Shape::Instructions],
        project: Some(".kilo/rules/estelle.md"),
        user: None,
        legacy: &[],
        detect: Some(".config/kilo"),
        skill: None,
        preamble: None,
        note: "Rebranded from kilocode.ai; the older .kilocode path is NOT written, it was never confirmed.",
    },
    Host {
        name: "trae",
        label: "Trae",
        shapes: &[Shape::Instructions],
        project: Some(".trae/rules/estelle.md"),
        user: None,
        legacy: &[],
        detect: Some(".trae"),
        skill: None,
        preamble: None,
        note: "Project path confirmed on docs.trae.cn; the user-scope path differs per build and is unwritten.",
    },
    Host {
        name: "aider",
        label: "Aider",
        shapes: &[Shape::Instructions],
        project: Some("CONVENTIONS.md"),
        user: None,
        legacy: &[],
        detect: None,
        skill: None,
        preamble: None,
        note: "WRITTEN BUT NOT WIRED: Aider reads this only if you add `read: CONVENTIONS.md` to .aider.conf.yml.",
    },
];
