#!/usr/bin/env python3
"""`estelle-client/secret_rules.json` is DATA FOR A DETECTOR, not configuration.

WHY THIS FILE EXISTS
--------------------
On 2026-08-30 GitHub's secret scanner opened 16 "Google API Key · Public leak" alerts against
`estelle-client/secret_rules.json` lines 845-860. That range is the entire `allowlist` array of
the `gcp-api-key` rule — the list of values Estelle's OWN scanner must never flag, because
gitleaks publishes them as documentation examples. One of them is the `AIza` prefix followed by
the lower-case alphabet and `1234567`. GitHub flagged our secret scanner's list of known-fake
keys. There was nothing to rotate.

No allowlisted value is quoted anywhere in this file, deliberately: clause 1 below asserts that
none appears outside the rule set, and a docstring that quoted one would be the first thing to
break it. That is not hypothetical — the first draft of this test quoted one, and the mutation
harness caught it before either file was committed (untracked files are invisible to `git grep`,
so it would have gone red on the commit, not on the write).

The two wrong fixes, and why:

  * Hand-editing the file to drop the allowlist. Its own header says
    `do not edit this file by hand`, it is regenerated from gitleaks' upstream config, and an
    empty allowlist makes Estelle's detector fire on gitleaks' own published examples in every
    customer repository that quotes them. Strictly worse than the alert.
  * Dismissing the alerts and moving on. They reopen the next time the file is regenerated, and
    the reasoning is not written down anywhere the next person will find it.

So the alerts are dismissed, `.github/secret_scanning.yml` excludes the path, and THIS test is
the thing that keeps the exclusion honest. It fails the moment the premise stops holding.

WHAT IT ASSERTS — one clause per line of the argument, so none is a silent exemption:

  1. Every allowlist value in the rule set is EITHER a credential-shaped literal that appears
     nowhere in this repository except inside that file's own `allowlist` arrays, OR a regex
     fragment that is not credential-shaped at all. Every entry falls in exactly one branch.
  2. Every allowlist entry compiles as a regex, and every literal one matches ITSELF — so the
     detector is guaranteed to allowlist it rather than report it. That is the operative sense of
     "unreachable as a real credential": our scanner can never emit it as a finding.
  3. Nothing in the repository reads a value out of the file and uses it. The only consumers are
     `include_str!` in the engine, the fork manifest's provenance entry, and this test.
  4. The file still declares its own provenance (generated, byte-derived from gitleaks upstream),
     so a hand-edit that strips the header is visible here rather than in a review no one does.
  5. `.github/secret_scanning.yml` exists, uses GitHub's documented `paths-ignore` key, and lists
     the file — so a regenerated rule set cannot reopen 16 alerts or be blocked by push
     protection.

Run: `python3 scripts/test-secret-rules-are-detector-data.py`
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES = ROOT / "estelle-client/secret_rules.json"
RULES_REL = "estelle-client/secret_rules.json"
EXCLUSIONS = ROOT / ".github/secret_scanning.yml"

# A value long enough and dense enough to be mistaken for a real credential. Below this a short
# regex fragment (`.+`, `example`) would drag in unrelated matches and the check would measure
# nothing. Entries under the bar must justify themselves as regex fragments instead (clause 1).
CREDENTIAL_MIN_LEN = 16
REGEX_METACHARACTERS = set(r".^$*+?{}[]\|()")

# Every place the rule set's PATH may be named. A new entry here is a deliberate decision that
# something else now depends on the file; a new entry that READS A VALUE out of it breaks the
# premise of the scanning exclusion and belongs in review, not in this list.
ALLOWED_REFERENCES = {
    RULES_REL,  # the file naming itself in its own metadata
    "estelle-client/src/secret_engine.rs",  # include_str! + the provenance docstring
    "fork-manifest.yaml",  # fork provenance entry
    ".github/secret_scanning.yml",  # the exclusion, which explains itself
    "scripts/test-secret-rules-are-detector-data.py",  # this test
}

failures: list[str] = []


def check(condition: bool, message: str) -> bool:
    if not condition:
        failures.append(message)
    return condition


def tracked_files_containing(literal: str) -> list[str]:
    """Tracked paths whose contents contain `literal`, as a fixed string."""
    result = subprocess.run(
        ["git", "grep", "-l", "-F", "--", literal],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    # 0 = matches, 1 = no matches; anything else is a real git failure and must not read as clean.
    if result.returncode not in (0, 1):
        raise SystemExit(f"git grep failed ({result.returncode}): {result.stderr.strip()}")
    return [line for line in result.stdout.splitlines() if line]


def allowlist_line_ranges(text: str) -> list[tuple[int, int]]:
    """1-based [start, end] line spans of every `"allowlist": [ ... ]` array in the file.

    Derived by bracket-matching from each `"allowlist":` key rather than by pattern-matching the
    values, so the spans describe the file's STRUCTURE. A value that sat outside an allowlist
    would fall outside every span and be reported, which is the whole point.
    """
    spans: list[tuple[int, int]] = []
    for match in re.finditer(r'"allowlist"\s*:\s*\[', text):
        depth = 0
        index = match.end() - 1
        while index < len(text):
            if text[index] == "[":
                depth += 1
            elif text[index] == "]":
                depth -= 1
                if depth == 0:
                    break
            index += 1
        else:  # pragma: no cover - unbalanced JSON would have failed json.load already
            raise SystemExit("unbalanced allowlist array in secret_rules.json")
        spans.append((text.count("\n", 0, match.start()) + 1, text.count("\n", 0, index) + 1))
    return spans


def line_numbers_of(text: str, literal: str) -> list[int]:
    return [n for n, line in enumerate(text.splitlines(), start=1) if literal in line]


def parse_paths_ignore(path: Path) -> list[str]:
    """The `paths-ignore` list, read without a YAML dependency.

    Deliberately a SHAPE assertion, not a permissive parse: the file must be exactly a
    `paths-ignore:` key followed by `  - "<glob>"` entries and comments. If it ever grows a
    construct this cannot read, that is a change to a security-relevant config and should stop
    here rather than be silently half-understood.
    """
    entries: list[str] = []
    seen_key = False
    for number, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if line == "paths-ignore:":
            check(not seen_key, f"{path.name}:{number}: paths-ignore declared twice")
            seen_key = True
            continue
        entry = re.fullmatch(r'\s+-\s+"([^"]+)"', line)
        if entry and seen_key:
            entries.append(entry.group(1))
            continue
        failures.append(f"{path.name}:{number}: unrecognised line {line!r}")
    check(seen_key, f"{path.name}: no top-level `paths-ignore` key (GitHub's documented schema)")
    return entries


def main() -> int:
    if not check(RULES.is_file(), f"{RULES_REL} is missing"):
        print("\n".join(failures), file=sys.stderr)
        return 1

    text = RULES.read_text()
    document = json.loads(text)
    rules = document["rules"]
    spans = allowlist_line_ranges(text)
    check(bool(spans), f"{RULES_REL}: no allowlist arrays found — the parser has drifted")

    # -- clause 4: the file still says what it is -------------------------------------------
    metadata = document.get("metadata", {})
    check(
        "generate_secret_rules.py" in metadata.get("generator", ""),
        f"{RULES_REL}: metadata.generator no longer names its generator — was this hand-edited?",
    )
    check(
        "gitleaks" in metadata.get("source", ""),
        f"{RULES_REL}: metadata.source no longer names gitleaks upstream",
    )
    check(
        metadata.get("rule_count") == len(rules),
        f"{RULES_REL}: metadata.rule_count={metadata.get('rule_count')} but {len(rules)} rules "
        "are present",
    )

    # -- clauses 1 and 2: every allowlist value, one branch each ------------------------------
    entries = [
        (rule["id"], value) for rule in rules for value in (rule.get("allowlist") or [])
    ]
    check(bool(entries), f"{RULES_REL}: no allowlist entries at all — the rule set looks empty")

    literals = 0
    fragments = 0
    for rule_id, value in entries:
        try:
            compiled = re.compile(value)
        except re.error as error:
            failures.append(f"{rule_id}: allowlist entry does not compile as a regex: {error}")
            continue

        is_literal = not (REGEX_METACHARACTERS & set(value))
        if is_literal and len(value) >= CREDENTIAL_MIN_LEN:
            literals += 1
            check(
                compiled.search(value) is not None,
                f"{rule_id}: allowlist entry does not match itself, so the detector could still "
                "report it as a finding",
            )
            locations = tracked_files_containing(value)
            if not check(
                locations == [RULES_REL],
                f"{rule_id}: a credential-shaped allowlist value appears outside the rule set: "
                f"{locations} — THIS IS A REAL FINDING, not a scanner false positive",
            ):
                continue
            outside = [
                number
                for number in line_numbers_of(text, value)
                if not any(start <= number <= end for start, end in spans)
            ]
            check(
                not outside,
                f"{rule_id}: value occurs at {RULES_REL}:{outside} which is outside every "
                "`allowlist` array",
            )
        else:
            fragments += 1
            # The other branch of clause 1, asserted rather than assumed: an entry that is exempt
            # from the "nowhere else" check must be a regex fragment, never a bare credential.
            check(
                not is_literal or len(value) < CREDENTIAL_MIN_LEN,
                f"{rule_id}: entry skipped the containment check without being a regex fragment",
            )

    # -- clause 3: nothing reads a value out of the file ---------------------------------------
    referencing = set(tracked_files_containing(RULES_REL))
    unexpected = sorted(referencing - ALLOWED_REFERENCES)
    check(
        not unexpected,
        f"{RULES_REL} is named by unreviewed files {unexpected}: confirm none of them reads a "
        "value out of it, then add them to ALLOWED_REFERENCES with a reason",
    )

    # -- clause 5: the exclusion exists and matches GitHub's documented schema ------------------
    if check(EXCLUSIONS.is_file(), ".github/secret_scanning.yml is missing"):
        ignored = parse_paths_ignore(EXCLUSIONS)
        check(
            RULES_REL in ignored,
            f".github/secret_scanning.yml does not exclude {RULES_REL}; it lists {ignored}",
        )
        check(
            len(ignored) <= 1000,
            "paths-ignore exceeds GitHub's documented 1,000-entry limit",
        )

    if failures:
        print("secret_rules.json detector-data contract FAILED", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1

    print(
        f"secret_rules.json is detector data: {len(rules)} rules, {len(entries)} allowlist "
        f"entries ({literals} credential-shaped literals confined to their own allowlist arrays, "
        f"{fragments} regex fragments), path excluded from GitHub secret scanning."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
